const domains = [
  "aol.com",
  "aol.it",
  "club-internet.fr",
  "clubinternet.fr",
  "free.fr",
  "gmail.com",
  "hotmail.com",
  "hanmail.net",
  "hotmail.be",
  "hotmail.fr",
  "icloud.com",
  "laposte.net",
  "live.com",
  "live.fr",
  "msn.com",
  "outlook.com",
  "outlook.fr",
  "orange.fr",
  "orange.net",
  "protonmail.com",
  "sfr.fr",
  "wanadoo.fr",
  "yahoo.com",
  "yahoo.fr",
];

export default domains;
